trigger: none

pr:
 branches:
  include:
  - master
 paths:
    include:
    - duffle/*
    exclude:
    - docs/README.md
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: $(Build.Repository.LocalPath)/duffle/build_bundle.sh
  displayName: 'Run duffle to build and validate the bundle'
