pr:
  branches:
    include:
    - master
  paths:
    include:
    - duffle/*
    exclude:
    -  duffle/README.md

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: |
    echo "Getting Duffle"
    duffle_version="/0.1.0-ralpha.5%2Benglishrose"
    curl https://github.com/deislabs/duffle/releases/download/${duffle_version}/duffle-linux-amd64 -L -o  $(Agent.ToolsDirectory)/duffle
    chmod +x $(Agent.ToolsDirectory)/duffle
    echo "Testing Duffle Works"
    $(Agent.ToolsDirectory)/duffle
  displayName: 'Run duffle to build the bundle'
