trigger: none

pr:
 branches:
  include:
  - master
 paths:
    include:
    - duffle/*
    exclude:
    - docs/README.md
    
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: $(Build.Repository.LocalPath)/build_bundle.sh
  env:
    agent_temp_directory: $(Agent.TempDirectory)
    repo_name: $(Build.Repository.Name)
    pr_number: $(System.PullRequest.PullRequestNumber)
    repo_local_path: $(Build.SourcesDirectory)
  displayName: 'Run duffle to build and validate the bundle'
